name: Compile typescript and push to dist/

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
      
        - name: Set Up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 16
      
        - name: Install Dependencies
          run: npm install
      
        - name: Build TypeScript
          run: npm run compile
      
        - name: Configure Git
          run: |
            git config --global user.email "iscosmos@outlook.com"
            git config --global user.name "onrirr"
            git config --global credential.helper store
        
        - name: Commit and Push Changes
          run: |
            git add dist/
            git commit -m "Compile TypeScript and push to dist/"
            git push https://github.com/${{ github.repository }}.git HEAD:main
          env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
