on:
    push:
      branches: [ main ]

      
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@master
  
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - name: npm install, build, and test
        run: |
          npm install
          npm run compile  # I want to deploy the folder that this command generates! 
      - name: push to github dist folder
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'build: ${{ github.sha }}'
          add: 'dist'
          force: true
          signoff: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}